M48
; DRILL file {KiCad 7.0.7} date 2023 September 08, Friday 15:18:39
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-08T15:18:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X4.6966Y-3.35
X5.4966Y-3.35
T2
X7.7Y-3.9
X7.7Y-4.9441
X7.9Y-3.6
X7.9Y-4.6441
T0
M30
